#
# Copyright (c) 2008 Hewlett-Packard Development Company, L.P.
#

SRCS= chains.tex dict.tex errors.tex gui.tex introduction.tex \
	omcf_arch.tex registration.tex savior.tex sensor.tex \
	copyright.tex

omcf_arch.pdf : ${SRCS}
	pdflatex omcf_arch.tex

clean :
	rm -f *.aux *.log 

clean-all :
	rm -f *.aux *.log *.pdf

